# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-02 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Restaurant',
        ),
        migrations.AddField(
            model_name='item',
            name='Restaurant',
            field=models.ManyToManyField(to='restaurant.Restaurant'),
        ),
        migrations.RemoveField(
            model_name='modifier',
            name='Item',
        ),
        migrations.AddField(
            model_name='modifier',
            name='Item',
            field=models.ManyToManyField(to='restaurant.Item'),
        ),
        migrations.RemoveField(
            model_name='secondarymodifier',
            name='modifier',
        ),
        migrations.AddField(
            model_name='secondarymodifier',
            name='modifier',
            field=models.ManyToManyField(to='restaurant.Modifier'),
        ),
    ]
